### ISSUE TITLE
On a fresh install on mac os x ...

### ISSUE THREAD

**Issue by oz123** [pwman3/pwman3#31]
```
Traceback (most recent call last):
  File "/Users/user/.virtualenvs/pw-test/bin/pwman3", line 52, in <module>
    main(args)
  File "/Users/user/.virtualenvs/pw-test/bin/pwman3", line 37, in main
    xselpath, dbtype, config = get_conf_options(args, OSX)
  File "/Users/user/.virtualenvs/pw-test/lib/python2.7/site-packages/pwman/__init__.py", line 133, in get_conf_options
    configp = get_conf(args)
  File "/Users/user/.virtualenvs/pw-test/lib/python2.7/site-packages/pwman/__init__.py", line 100, in get_conf
    configp = config.Config(args.cfile, default_config)
  File "/Users/user/.virtualenvs/pw-test/lib/python2.7/site-packages/pwman/util/config.py", line 65, in __init__
    self.parser = self._load(defaults)
  File "/Users/user/.virtualenvs/pw-test/lib/python2.7/site-packages/pwman/util/config.py", line 70, in _load
    with open(self.filename) as f:
IOError: [Errno 2] No such file or directory: '/Users/user/.pwman/config'
```

**Comment by oz123** [comment]
Apparently this happens on any OS on fresh install.
