### ISSUE TITLE
TypeError: Incorrect padding via tags command

### ISSUE THREAD

**Issue by gadeleon** [pwman3/pwman3#41]
Version 0.7.0 & 0.7.1 in an altinstall of Python2.7

Affects imported databases and new databases.

Steps:
1) Launch PWman3
2) input master password
3) enter tags, the following error happens:

pwman> tags
Tags:
Traceback (most recent call last):
  File "/opt/python27/bin/pwman3", line 9, in <module>
    load_entry_point('pwman3==0.7.1', 'console_scripts', 'pwman3')()
  File "/opt/python27/lib/python2.7/site-packages/pwman/ui/cli.py", line 113, in main
    cli.cmdloop()
  File "/opt/python27/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/opt/python27/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/opt/python27/lib/python2.7/site-packages/pwman/ui/baseui.py", line 314, in do_tags
    print(ce.decrypt(t).decode())
  File "/opt/python27/lib/python2.7/site-packages/pwman/util/crypto_engine.py", line 173, in decrypt
    AES.block_size))
  File "/opt/python27/lib/python2.7/site-packages/pwman/util/crypto_engine.py", line 36, in <lambda>
    DecodeAES = lambda c, e: c.decrypt(base64.b64decode(e)).rstrip()
  File "/opt/python27/lib/python2.7/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

**Comment by oz123** [comment]
It seems to me you have a old database with from 0.5.x
See here http://pwman3.readthedocs.org/en/latest/install.html. 

There are instructions on how to upgrade.

**Comment by oz123** [comment]
@gadeleon can you provide feedback? Did exporting your database and importing it helps?

**Comment by gadeleon** [comment]
@oz123 Yeah, I must have misread the documentation for upgrading for 0.5.X. The 0.5.X database I exported was not 'converted' into a 0.7.X compatible until I exported it from the 0.7 version and re-importing it. Afterwards everything started functioning as expected. 

In short: 

* Export 0.5.X database
* Import into 0.7
* Export from 0.7
* Import back into 0.7
