### ISSUE TITLE
Installing in windows is plagued with bugs

### ISSUE THREAD

**Issue by oz123** [pwman3/pwman3#42]
For example:
```
Collecting pwman3
  Using cached pwman3-0.7.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\svenja~1\appdata\local\temp\pip-build-veykeg\pwman3\setup.py", line 325, in <module>
        install_requires.append('pyreadeline')
    AttributeError: 'tuple' object has no attribute 'append'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\svenja~1\appdata\local\temp\pip-build-veykeg\pwman3                                                                                                                           
```

**Comment by oz123** [comment]
Fixed in 0.7.3
