### ISSUE TITLE
fresh install from pypi - no module named colorama

### ISSUE THREAD

**Issue by oz123** [pwman3/pwman3#43]
pip install pwman3
Collecting pwman3
  Using cached pwman3-0.7.4.tar.gz
Collecting pycrypto>=2.6 (from pwman3)
  Using cached pycrypto-2.6.1.tar.gz
Collecting colorama>=0.2.4 (from pwman3)
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Building wheels for collected packages: pwman3, pycrypto
  Running setup.py bdist_wheel for pwman3 ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-RCQX6W/pwman3/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpLimb4spip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/pwman
  copying pwman/__init__.py -> build/lib.linux-x86_64-2.7/pwman
  creating build/lib.linux-x86_64-2.7/pwman/ui
  copying pwman/ui/win.py -> build/lib.linux-x86_64-2.7/pwman/ui
  copying pwman/ui/baseui.py -> build/lib.linux-x86_64-2.7/pwman/ui
  copying pwman/ui/cli.py -> build/lib.linux-x86_64-2.7/pwman/ui
  copying pwman/ui/mac.py -> build/lib.linux-x86_64-2.7/pwman/ui
  copying pwman/ui/tools.py -> build/lib.linux-x86_64-2.7/pwman/ui
  copying pwman/ui/__init__.py -> build/lib.linux-x86_64-2.7/pwman/ui
  creating build/lib.linux-x86_64-2.7/pwman/exchange
  copying pwman/exchange/__init__.py -> build/lib.linux-x86_64-2.7/pwman/exchange
  copying pwman/exchange/importer.py -> build/lib.linux-x86_64-2.7/pwman/exchange
  creating build/lib.linux-x86_64-2.7/pwman/util
  copying pwman/util/config.py -> build/lib.linux-x86_64-2.7/pwman/util
  copying pwman/util/__init__.py -> build/lib.linux-x86_64-2.7/pwman/util
  copying pwman/util/callback.py -> build/lib.linux-x86_64-2.7/pwman/util
  copying pwman/util/crypto_engine.py -> build/lib.linux-x86_64-2.7/pwman/util
  creating build/lib.linux-x86_64-2.7/pwman/data
  copying pwman/data/nodes.py -> build/lib.linux-x86_64-2.7/pwman/data
  copying pwman/data/convertdb.py -> build/lib.linux-x86_64-2.7/pwman/data
  copying pwman/data/factory.py -> build/lib.linux-x86_64-2.7/pwman/data
  copying pwman/data/database.py -> build/lib.linux-x86_64-2.7/pwman/data
  copying pwman/data/__init__.py -> build/lib.linux-x86_64-2.7/pwman/data
  creating build/lib.linux-x86_64-2.7/pwman/data/drivers
  copying pwman/data/drivers/mysql.py -> build/lib.linux-x86_64-2.7/pwman/data/drivers
  copying pwman/data/drivers/sqlite.py -> build/lib.linux-x86_64-2.7/pwman/data/drivers
  copying pwman/data/drivers/postgresql.py -> build/lib.linux-x86_64-2.7/pwman/data/drivers
  copying pwman/data/drivers/__init__.py -> build/lib.linux-x86_64-2.7/pwman/data/drivers
  copying pwman/data/drivers/mongodb.py -> build/lib.linux-x86_64-2.7/pwman/data/drivers
  running egg_info
  writing requirements to pwman3.egg-info/requires.txt
  writing pwman3.egg-info/PKG-INFO
  writing top-level names to pwman3.egg-info/top_level.txt
  writing dependency_links to pwman3.egg-info/dependency_links.txt
  writing entry points to pwman3.egg-info/entry_points.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'pwman3.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'pwman3.egg-info/SOURCES.txt'
  creating build/lib.linux-x86_64-2.7/pwman/ui/templates
  copying pwman/ui/templates/ajax.tpl -> build/lib.linux-x86_64-2.7/pwman/ui/templates
  copying pwman/ui/templates/base.tpl -> build/lib.linux-x86_64-2.7/pwman/ui/templates
  copying pwman/ui/templates/edit.tpl -> build/lib.linux-x86_64-2.7/pwman/ui/templates
  copying pwman/ui/templates/foxy.html -> build/lib.linux-x86_64-2.7/pwman/ui/templates
  copying pwman/ui/templates/login.tpl -> build/lib.linux-x86_64-2.7/pwman/ui/templates
  copying pwman/ui/templates/main.tpl -> build/lib.linux-x86_64-2.7/pwman/ui/templates
  copying pwman/ui/templates/view.tpl -> build/lib.linux-x86_64-2.7/pwman/ui/templates
  creating build/lib.linux-x86_64-2.7/pwman/ui/templates/static
  creating build/lib.linux-x86_64-2.7/pwman/ui/templates/static/css
  copying pwman/ui/templates/static/css/main.css -> build/lib.linux-x86_64-2.7/pwman/ui/templates/static/css
  copying pwman/ui/templates/static/css/normalize.css -> build/lib.linux-x86_64-2.7/pwman/ui/templates/static/css
  copying pwman/ui/templates/static/css/normalize.min.css -> build/lib.linux-x86_64-2.7/pwman/ui/templates/static/css
  creating build/lib.linux-x86_64-2.7/pwman/ui/templates/static/js
  copying pwman/ui/templates/static/js/main.js -> build/lib.linux-x86_64-2.7/pwman/ui/templates/static/js
  copying pwman/ui/templates/static/js/plugins.js -> build/lib.linux-x86_64-2.7/pwman/ui/templates/static/js
  creating build/lib.linux-x86_64-2.7/pwman/ui/templates/static/js/vendor
  copying pwman/ui/templates/static/js/vendor/jquery-1.11.0.js -> build/lib.linux-x86_64-2.7/pwman/ui/templates/static/js/vendor
  copying pwman/ui/templates/static/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js -> build/lib.linux-x86_64-2.7/pwman/ui/templates/static/js/vendor
  running build_manpage
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-RCQX6W/pwman3/setup.py", line 369, in <module>
      'console_scripts': ['pwman3 = pwman.ui.cli:main']
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 971, in run_command
      cmd_obj.ensure_finalized()
    File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
      self.finalize_options()
    File "/tmp/pip-build-RCQX6W/pwman3/setup.py", line 87, in finalize_options
      raise err
  ImportError: No module named colorama
  
  ----------------------------------------
  Failed building wheel for pwman3
  Running setup.py clean for pwman3
  Running setup.py bdist_wheel for pycrypto ... done
  Stored in directory: /home/oznt/.cache/pip/wheels/80/1f/94/f76e9746864f198eb0e304aeec319159fa41b082f61281ffce
Successfully built pycrypto
Failed to build pwman3
Installing collected packages: pycrypto, colorama, pwman3
  Running setup.py install for pwman3 ... done
Successfully installed colorama pwman3 pycrypto
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by oz123** [comment]
fixed in version 0.8
