### ISSUE TITLE
After update, printing new nodes fails

### ISSUE THREAD

**Issue by donnm** [pwman3/pwman3#53]
Updated from 0.5.1d by exporting and importing CSV. New entries added are saved but when printed cause the following crash:

```
pwman> new
Username: Test
Password (leave empty to create one):
Password length (default: 8):
Url: https://site.url  
Notes: My site
Tags: 
pwman> print 158
Traceback (most recent call last):
  File "/usr/local/bin/pwman3", line 9, in <module>
    load_entry_point('pwman3==0.9.5', 'console_scripts', 'pwman3')()
  File "/usr/local/lib/python3.5/dist-packages/pwman3-0.9.5-py3.5.egg/pwman/ui/cli.py", line 138, in main
    cli.cmdloop()
  File "/usr/lib/python3.5/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.5/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.5/dist-packages/pwman3-0.9.5-py3.5.egg/pwman/ui/baseui.py", line 474, in do_print
    print(node)
  File "/usr/local/lib/python3.5/dist-packages/pwman3-0.9.5-py3.5.egg/pwman/data/nodes.py", line 40, in __str__
    tags =",".join(t.decode() for t in self.tags) if len(self.tags) > 1 else self.tags[0].decode()  # noqa
IndexError: list index out of range

```
Editing and deleting seem to work fine. A workaround to print the password is thus to edit it and not save the changes.

Printing entries that existed prior to the update seems to work correctly.

**Comment by oz123** [comment]
I can confirm this bug. The problem is that there are no tags. I should fix soon.
