### ISSUE TITLE
error printing password

### ISSUE THREAD

**Issue by gjover** [pwman3/pwman3#83]
Asking for printing a password one gets the following error:

```
pwman> p 4
Please type in your master password:
Username: aaaaa    
Password: xxxxxx
URL:           
Notes: bla bla
Tags: AA, BB

Traceback (most recent call last):
  File "/usr/bin/pwman3", line 33, in <module>
    sys.exit(load_entry_point('pwman3==0.12.1', 'console_scripts', 'pwman3')())
  File "/usr/lib/python3/dist-packages/pwman/ui/cli.py", line 152, in main
    cli.cmdloop()
  File "/usr/lib/python3.9/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.9/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/lib/python3/dist-packages/pwman/ui/baseui.py", line 163, in do_p
    self.do_print(arg)
  File "/usr/lib/python3/dist-packages/pwman/ui/baseui.py", line 526, in do_print
    flushtimeout = int(flushtimeout) if flushtimeout else 10
ValueError: invalid literal for int() with base 10: '5 # Number of seconds before the screen is clean after a print. Set to 0 to disable.'

```

Installed in debian 11 with apt.
0.12.1-2 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages

config file:
```
[Global]
umask = 0100 # The umask in which database and configuration files are written.
colors = yes # set to `no` to supress color in output. This is useful for breil terminals
cls_timeout = 5 # Number of seconds before the screen is clean after a print. Set to 0 to disable.
cp_timeout = 10 # number of seconds before the clipboard is erased.
save = True #  whether the Configuring file should be saved
lock_timeout = 600
xsel = 

[Database]
dburi = sqlite:///home/myuser/.local/share/pwman/pwman.db

[Readline]
history = /home/myuser/.local/share/pwman/history

[Crypto]
supress_warning = no

[Updater]
supress_version_check = no # set to `yes` to supress check for newer versions of pwman3
client_info = "" #  sha256 digest of host name and username, used for identifying the client

[UI]
url_length = 22 # the max length of URL to show. Longer URLs are trimmed
url_pad = 25 # the padding of the URL in `line_format`
user_pad = 25 # the padding of the user name in `line_format`
tag_pad = 20 # the padding of tags in the `line_format
line_format = {ID:<3} {USER:<{user_pad}}{URL:<{url_pad}}{Tags:<{tag_pad}}


```

**Comment by oz123** [comment]
Can you comment the offending key :
```
#cls_timeout = 5
```
Maybe this helps?
